sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t nsreenivas1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nsreenivas1/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "bucket-name"
  bucket_path: "docker"
  on:
    branch: master